const underscore = "_";

const alphabet = [
	"a",
	"b",
	"c",
	"d",
	"e",
	"f",
	"g",
	"h",
	"i",
	"j",
	"k",
	"l",
	"m",
	"n",
	"o",
	"p",
	"q",
	"r",
	"s",
	"t",
	"u",
	"v",
	"w",
	"x",
	"y",
	"z",
];

const categoryData = {
	Automobiles: [
		"volkswagen scirocco",
		"koenigsegg gemera",
		"lamborghini murcielago",
		"maserati quattroporte",
		"ssangyong tivoli",
		"pagani huayara",
		"porsche cayenne",
		"ferrari testarossa",
		"chevrolet corvette stingray",
		"ford mustang shelby",
	],
	Famous_Scientists: [
		"albert einstein",
		"nikola tesla",
		"charles darwin",
		"thomas edison",
		"marie curie",
		"stephen hawking",
		"george washington carver",
		"alexander graham bell",
		"archimedes",
		"louis pasteur",
	],
	Movies: [
		"the devil wears prada",
		"a series of unfortunate events",
		"the wizard of oz",
		"one flew over the cuckoo's nest",
		"no country for old men",
		"the matrix reloaded",
		"austin powers: the spy who shagged me",
		"lost in translation",
		"eternal sunshine of the spotless mind",
		"slumdog millionare",
	],
	Anime_Titles: [
		"attack on titan",
		"neon genesis evangelion",
		"sword art online",
		"samurai champloo",
		"fullmetal alchemist",
		"jujutsu kaisen",
		"hunter x hunter",
		"rurouni kenshin",
		"ghost in the shell",
		"one punch man",
	],
	Classical_Music_Composers: [
		"wolfgang amadeus mozart",
		"claude debussy",
		"pyotr ilyich tchaikovsky",
		"ludwig van beethoven",
		"joseph haydn",
		"johann sebastian bach",
		"johannes brahms",
		"richard wagner",
		"frederic chopin",
		"antonio vivaldi",
	],
	ABBA_Songs: [
		"dancing queen",
		"super trouper",
		"take a chance on me",
		"fernando",
		"gimme gimme gimme",
		"mamma mia",
		"the winner takes it all",
		"waterloo",
		"does your mother know",
		"lay all your love on me",
	],
	Hans_Zimmer_Film_Scores: [
		"gladiator",
		"pirates of the caribbean",
		"sherlock holmes",
		"inception",
		"the dark knight",
		"the lion king",
		"dune",
		"the da vinci code",
		"interstellar",
		"pearl harbor",
		"no time to die",
		"top gun: maverick",
		"dunkirk",
		"the boss baby",
		"batman v superman: dawn of justice",
		"kung fu panda",
		"king arthur",
		"black hawk down",
	],
};

module.exports = {
	underscore,
	alphabet,
	categoryData,
};
